name: Athena Global Energy Solutions
favicon: null
layout_spectrum: 0.2495
typography_spectrum: 0.42705
title: Athena Global Energy Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#133149'
    - '#acacac'
    - '#0dc3ce'
    - '#ecb102'
  brandStrength: 1
  lightness: 0.10754015645943582
  saturation: 0.08072717860341072
  rhythmicContrast: 1
purpose: []
